from __future__ import division
from math import *
import jmp_score as jmp


""" ==================================================================
 Copyright(C) 2016 SAS Institute Inc.All rights reserved.
 
 Notice:
 The following permissions are granted provided that the
 above copyright and this notice appear in the score code and
 any related documentation.Permission to copy, modify
 and distribute the score code generated using
 JMP(R) software is limited to customers of SAS Institute Inc. ("SAS")
 and successive third parties, all without any warranty, express or
 implied, or any other obligation by SAS.SAS and all other SAS
 Institute.Inc.product and service names are registered
 trademarks or trademarks of SAS Institute Inc.in the USA
 and other countries.Except as contained in this notice,
 the name of the SAS Institute Inc. and JMP shall not be used in
 the advertising or promotion of products or services without
 prior written authorization from SAS Institute Inc.
 ================================================================== """

""" Python code generated by JMP v13.0.0 """

def getModelMetadata():
	return {"creator": "Partial Least Squares", "modelName": "", "predicted": "1/ {Log EC50}", "table": "QSAR-ANOVA", "version": "13.0.0", "timestamp": "2020-04-21T19:21:56Z"}


def getInputMetadata():
    return {
        "h_pavgQ": "float",
        "SlogP_VSA8": "float",
        "PEOE_VSA-6": "float",
        "h_pstates": "float",
        "mutagenic": "float",
        "MNDO_E": "float",
        "FASA+": "float",
        "FASA-": "float",
        "reactive": "float",
        "PM3_E": "float",
        "GCUT_PEOE_0": "float",
        "AM1_Eele": "float",
        "vsurf_CP": "float",
        "SlogP_VSA4": "float",
        "vsurf_CW2": "float",
        "ASA": "float",
        "apol": "float",
        "GCUT_SLOGP_2": "float",
        "vsurf_Wp1": "float",
        "density": "float",
        "PM3_dipole": "float",
        "diameter": "float",
        "logP(o/w)": "float",
        "ASA_P": "float",
        "FASA_H": "float",
        "h_emd": "float",
        "MNDO_dipole": "float",
        "dipoleX": "float",
        "PEOE_VSA-1": "float",
        "PEOE_VSA+5": "float",
        "BCUT_SMR_3": "float",
        "vsurf_W6": "float",
        "vsurf_A": "float",
        "npr2": "float",
        "vsurf_Wp4": "float",
        "SlogP_VSA6": "float",
        "vdw_area": "float",
        "pmiX": "float",
        "Kier2": "float",
        "GCUT_SLOGP_0": "float",
        "Q_VSA_FPOL": "float",
        "vsurf_EDmin3": "float",
        "SMR_VSA1": "float",
        "vsurf_EDmin1": "float",
        "MNDO_Eele": "float"
	}


def getOutputMetadata():
    return {
        "Pred Formula 1/ {Log EC50}": "float"
	}


def score(indata, outdata):
    # _temp0

    _temp0 = -0.022502570262418 * indata['h_pavgQ']
    _temp0 += -0.000220274065228523 * indata['SlogP_VSA8']
    _temp0 += -0.00056426046130764 * indata['PEOE_VSA-6']
    _temp0 += 0.00736063077184102 * indata['h_pstates']
    _temp0 += 0.0245821058890359 * indata['mutagenic']
    _temp0 += 0.0000000647681942032 * indata['MNDO_E']
    _temp0 += 0.0536009475113163 * indata['FASA+']
    _temp0 += -0.00501765458836686 * indata['FASA-']
    _temp0 += 0.0139133838895935 * indata['reactive']
    _temp0 += 0.0000000098330258915 * indata['PM3_E']
    _temp0 += -0.0838561916135386 * indata['GCUT_PEOE_0']
    _temp0 += -0.0000000161738633998 * indata['AM1_Eele']
    _temp0 += 0.0713871561807966 * indata['vsurf_CP']
    _temp0 += 0.00024417403408819 * indata['SlogP_VSA4']
    _temp0 += 0.0142109668939178 * indata['vsurf_CW2']
    _temp0 += 0.0000542944674942034 * indata['ASA']
    _temp0 += -0.000579936117236134 * indata['apol']
    _temp0 += -0.102119063042627 * indata['GCUT_SLOGP_2']
    _temp0 += 0.0000052255046588837 * indata['vsurf_Wp1']
    _temp0 += 0.0977645923174864 * indata['density']
    _temp0 += -0.000666716814108074 * indata['PM3_dipole']
    _temp0 += -0.00327045675941807 * indata['diameter']
    _temp0 += 0.00655893173321761 * indata['logP(o/w)']
    _temp0 += -0.000160065223561349 * indata['ASA_P']
    _temp0 += -0.0839523075540544 * indata['FASA_H']
    _temp0 += 0.000799243155695222 * indata['h_emd']
    _temp0 += 0.00029648978123998 * indata['MNDO_dipole']
    _temp0 += -0.0013089403805793 * indata['dipoleX']
    _temp0 += -0.000132345178574591 * indata['PEOE_VSA-1']
    _temp0 += -0.000285434633902433 * indata['PEOE_VSA+5']
    _temp0 += 0.0356755542638068 * indata['BCUT_SMR_3']
    _temp0 += 0.000526182859295923 * indata['vsurf_W6']
    _temp0 += -0.00118958201136507 * indata['vsurf_A']
    _temp0 += 0.00118774818165878 * indata['npr2']
    _temp0 += -0.0000079169959973049 * indata['vsurf_Wp4']
    _temp0 += 0.00145124660944999 * indata['SlogP_VSA6']
    _temp0 += -0.0000957356457358781 * indata['vdw_area']
    _temp0 += 0.0000012635417715436 * indata['pmiX']
    _temp0 += 0.00613470415902608 * indata['Kier2']
    _temp0 += 0.00112599476300111 * indata['GCUT_SLOGP_0']
    _temp0 += 0.0342268941363964 * indata['Q_VSA_FPOL']
    _temp0 += 0.0210751113932589 * indata['vsurf_EDmin3']
    _temp0 += -0.000126492365707446 * indata['SMR_VSA1']
    _temp0 += -0.0102781433996679 * indata['vsurf_EDmin1']
    _temp0 += -0.0000000024539003129 * indata['MNDO_Eele']
    _temp0 += -0.313344263672212
    outdata['Pred Formula 1/ {Log EC50}'] = _temp0

    return outdata['Pred Formula 1/ {Log EC50}']


